# Generated by Django 4.2.1 on 2023-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_telegramgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
