# Generated by Django 4.2.15 on 2024-08-14 15:19

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0004_telegramgroup_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="InPersonMovieSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("imdb_id", models.CharField(max_length=64)),
                ("tennant_id", models.CharField(max_length=64)),
                ("title", models.TextField()),
                ("runtime", models.IntegerField()),
                ("genre", models.TextField(blank=True, null=True)),
                ("meta", models.TextField(null=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("imdb_update", models.DateTimeField(auto_now_add=True, null=True)),
                ("theater_datetime", models.DateTimeField(blank=True, null=True)),
                ("theater_location", models.TextField(blank=True, null=True)),
                ("attendees", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
