# Generated by Django 4.2.15 on 2024-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_inpersonmoviesuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="inpersonmoviesuggestion",
            name="showing_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
