# Generated by Django 4.2.15 on 2024-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_inpersonmoviesuggestion_showing_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inpersonmoviesuggestion",
            name="meta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inpersonmoviesuggestion",
            name="runtime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inpersonmoviesuggestion",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
