# Generated by Django 4.2.15 on 2024-08-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_inpersonmoviesuggestion_meta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inpersonmoviesuggestion",
            name="showing_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="inpersonmoviesuggestion",
            name="theater_location",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
