# Generated by Django 4.2.15 on 2024-08-14 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0009_alter_inpersonmoviesuggestion_attendees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inpersonmoviesuggestion",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
