# Generated by Django 4.2.15 on 2024-08-14 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_inpersonmoviesuggestion_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
