# Generated by Django 4.2.15 on 2025-05-05 08:24

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('tmdb_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='inpersonmoviesuggestion',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviesuggestion',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='secret_hash',
            field=models.CharField(default=web.models.get_token, max_length=64),
        ),
    ]
