# Generated by Django 4.2.15 on 2025-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_companyinformation_inpersonmoviesuggestion_tmdb_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('iso', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='moviesuggestion',
            name='production_companies',
            field=models.ManyToManyField(blank=True, to='web.companyinformation'),
        ),
        migrations.AddField(
            model_name='moviesuggestion',
            name='tmdb_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moviesuggestion',
            name='production_countries',
            field=models.ManyToManyField(blank=True, to='web.productioncountry'),
        ),
    ]
