# Generated by Django 4.2.15 on 2025-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_productioncountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='name',
            field=models.TextField(),
        ),
    ]
